source "https://supermarket.chef.io"

cookbook "apt"
cookbook "ntp"
cookbook 'hostnames'
cookbook 'timezone-ii', git: 'https://github.com/L2G/timezone-ii.git'
cookbook 'rabbitmq'
cookbook 'java'
cookbook 'maven'
cookbook 'memcached'
cookbook 'messagingserver', path: './cookbooks/messagingserver'