# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
 
  config.vm.hostname = "messagingserver-springws"

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box"

  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network", bridge: "eth0"

  config.omnibus.install_url = "https://www.chef.io/chef/install.sh"

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../Berksfile"

  config.vm.provision "chef_solo" do |chef| 
    chef.cookbooks_path = ["../cookbooks"]

    chef.add_recipe "memcached"
    chef.add_recipe "messagingserver::springws.etcd"
    chef.add_recipe "messagingserver::springws.http"
    chef.add_recipe "messagingserver::springws.websocket"    

    chef.json = {
      :name => "messagingserver-springws",
      :messagingserver => {
        :webapp_host => "192.168.33.10"
      }
    }
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

end


