name             'messagingserver'
maintainer       'Bertrand ZANNI'
maintainer_email 'zanni.bertrand@gmail.com'
license          ''
description      ''
long_description ''
version          '0.1.0'

depends 'apt'
depends 'ntp'
depends 'hostnames'
depends 'timezone-ii'
depends 'rabbitmq'
depends 'java'